components:
  schemas:
    ApiResponse:
      properties:
        code:
          description: 响应代码
          type: string
        data:
          description: 响应数据
        message:
          description: 响应消息
          type: string
        metadata:
          description: 元数据
          type: object
        request_id:
          description: 请求ID
          type: string
        success:
          description: 请求是否成功
          type: boolean
        timestamp:
          description: 响应时间戳
          format: date-time
          type: string
      required:
      - success
      - message
      type: object
    ErrorResponse:
      properties:
        code:
          description: 错误代码
          type: string
        details:
          description: 错误详情
          type: object
        message:
          description: 错误消息
          type: string
        success:
          example: false
          type: boolean
      required:
      - success
      - message
      type: object
    PagedResponse:
      properties:
        data:
          description: 数据列表
          items: {}
          type: array
        message:
          type: string
        pagination:
          properties:
            has_next:
              description: 是否有下一页
              type: boolean
            has_prev:
              description: 是否有上一页
              type: boolean
            page:
              description: 当前页码
              type: integer
            page_size:
              description: 每页大小
              type: integer
            total:
              description: 总记录数
              type: integer
            total_pages:
              description: 总页数
              type: integer
          type: object
        success:
          type: boolean
      required:
      - success
      - message
      - pagination
      type: object
info:
  description: SuperRPG游戏API文档
  title: SuperRPG API
  version: 1.0.0
openapi: 3.0.0
paths:
  /extensions:
    get:
      description: null
      parameters: []
      responses:
        '200':
          content:
            application/json:
              example:
                data: {}
                success: true
              schema:
                type: object
          description: 成功响应
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 请求错误
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 资源未找到
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 服务器错误
      summary: extensions_info
      tags:
      - extensions
  /health:
    get:
      description: null
      parameters: []
      responses:
        '200':
          content:
            application/json:
              example:
                data: {}
                success: true
              schema:
                type: object
          description: 成功响应
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 请求错误
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 资源未找到
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 服务器错误
      summary: health_check
      tags:
      - health
  /info:
    get:
      description: null
      parameters: []
      responses:
        '200':
          content:
            application/json:
              example:
                data: {}
                success: true
              schema:
                type: object
          description: 成功响应
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 请求错误
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 资源未找到
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 服务器错误
      summary: app_info
      tags:
      - info
  /modules:
    get:
      description: null
      parameters: []
      responses:
        '200':
          content:
            application/json:
              example:
                data: {}
                success: true
              schema:
                type: object
          description: 成功响应
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 请求错误
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 资源未找到
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 服务器错误
      summary: modules_info
      tags:
      - modules
servers:
- description: 开发服务器
  url: http://localhost:8000
tags:
- description: default相关API
  name: default
- description: health相关API
  name: health
- description: info相关API
  name: info
- description: modules相关API
  name: modules
- description: extensions相关API
  name: extensions
